In [1]:
#sciezka z danymi
%cd "C:\Users\Dawid\Desktop\kurs\jdszr4-animalsi\wino"

C:\Users\Dawid\Desktop\kurs\jdszr4-animalsi\wino


In [61]:
#glowne biblioteki
import pandas as pd
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import *
from sklearn.model_selection import GridSearchCV 
from time import time 
from winsound import Beep

In [2]:
#wlasny modul
from dane.dane_wsadowe import *

lista zmiennych: 
 ['X', 'Y', 'X_train_all', 'X_test', 'Y_train_all', 'Y_test', 'X_train_reduced', 'X_val', 'Y_train_reduced', 'Y_val', 'X_train_all_scaled', 'X_test_scaled', 'X_val_scaled', 'X_train_reduced_scaled', 'X_train_all_scaled_PCA', 'X_test_scaled_PCA', 'X_train_reduced_scaled_PCA', 'X_val_scaled_PCA']


**1. Prosty model lasow losowych jako benchmark**

a) dane nieprzetworzone 

In [8]:
#wyjdzmy od prostego modelu na domyslnych parametrach
model_rf1 = RandomForestClassifier()
model_rf1.fit(X_train_reduced,Y_train_reduced)
pred_rf1 = model_rf1.predict(X_val)

In [11]:
#ocena jakosci modelu nr 1
rf1_cnf_matrix = confusion_matrix(Y_val, pred_rf1)
rf1_cnf_raport = classification_report(Y_val, pred_rf1)
print(rf1_cnf_raport)
print(rf1_cnf_matrix)

              precision    recall  f1-score   support

           1       0.00      0.00      0.00         7
           2       0.81      0.94      0.87       101
           3       0.45      0.25      0.32        20

    accuracy                           0.78       128
   macro avg       0.42      0.40      0.40       128
weighted avg       0.71      0.78      0.74       128

[[ 0  7  0]
 [ 0 95  6]
 [ 0 15  5]]


Ocena pierwszego modelu, model jak mozna bylo się spodziewać dobrze przewiduje klase najbardziej liczna, a w ogóle nie trafią w klase 1.

b) dane przeskalowane

In [23]:
#wyjdzmy od prostego modelu na domyslnych parametrach
model_rf2 = RandomForestClassifier()
model_rf2.fit(X_train_reduced_scaled,Y_train_reduced)
pred_rf2 = model_rf2.predict(X_val_scaled)

In [24]:
#ocena jakosci modelu nr 1
rf2_cnf_matrix = confusion_matrix(Y_val, pred_rf2)
rf2_cnf_raport = classification_report(Y_val, pred_rf2)
print(rf2_cnf_raport)
print(rf2_cnf_matrix)

              precision    recall  f1-score   support

           1       0.00      0.00      0.00         7
           2       0.82      0.93      0.87       101
           3       0.50      0.35      0.41        20

    accuracy                           0.79       128
   macro avg       0.44      0.43      0.43       128
weighted avg       0.73      0.79      0.75       128

[[ 0  7  0]
 [ 0 94  7]
 [ 0 13  7]]


C:\Users\Dawid\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Przy przeskalowanych danych poprawił nam się nieznacznie współczynik F1 dla klasy 3, ale wciąż nie udało nam się sklasyfikować żadnej obserwacji jako klasa 1.

c) dane PCA

In [25]:
#wyjdzmy od prostego modelu na domyslnych parametrach
model_rf3 = RandomForestClassifier()
model_rf3.fit(X_train_reduced_scaled_PCA,Y_train_reduced)
pred_rf3 = model_rf3.predict(X_val_scaled_PCA)

In [26]:
#ocena jakosci modelu nr 1
rf3_cnf_matrix = confusion_matrix(Y_val, pred_rf3)
rf3_cnf_raport = classification_report(Y_val, pred_rf3)
print(rf3_cnf_raport)
print(rf3_cnf_matrix)

              precision    recall  f1-score   support

           1       1.00      0.14      0.25         7
           2       0.82      0.93      0.87       101
           3       0.46      0.30      0.36        20

    accuracy                           0.79       128
   macro avg       0.76      0.46      0.50       128
weighted avg       0.78      0.79      0.76       128

[[ 1  6  0]
 [ 0 94  7]
 [ 0 14  6]]


Ten wariant w końcu sklasyfikował nam cos poprawnie dla klasy 1, ale w większości błędnie.

**2. Znajdzmy najlepsze parametry dla tego modelu**

In [53]:
#zacznijmy od małego zestawu, by dostrzec czy jest w ogóle jakas poprawa
params_rf4 = {"max_depth"        :list(range(2, 15, 2)),
              "n_estimators"     :list(range(50,211,40)),
              "min_samples_leaf" :list(range(2, 21, 3)),
              "max_features"     :[3,6,9,None]
}

In [66]:
r=  0   # policzymy ile jest mozliwych kombinacji parametrow
for j in params_rf4.values():
    s=len(j)
    r += s
r

0.0010001659393310547

In [ ]:
#zdefijmy objekt sprawdzajacy nasze parametry
grid_search =  GridSearchCV(RandomForestClassifier(),param_grid = params_rf4,cv =5,verbose = 1,njobs = 1).fit(X_train_all,Y_train_all)
Beep(400,1000)

In [ ]:
#zrob potem model na zmiennych PCA 

In [ ]:
#zrob AUC - jak to zrobic dla 3 klas, jak przypisac pary, wagi??? - Michała cisnij !!!